### ISSUE TITLE
[repo 살리기 프로젝트] 각 알고리즘 코테 유형 분석한 걸로 문제집 제작 및 정리

### ISSUE THREAD

**Issue by tony9402** [tony9402/baekjoon#1]
파이썬, 자바, C++로 풀어서 정리

**Comment by pingipsolo** [comment]
Pungi의 정중한 인사.

제 이메일이 당신을 잘 찾길 바랍니다. 서로 모르는 사이에 연락을 하는 것이 이례적인 일이라는 것을 알고 있습니다. 무례하게 하려는 것이 아니라 죄송합니다. 저에 대해 조금 더 말씀드려야 할 것 같아요. 저는 비즈니스 개발 전문가입니다. 귀하의 지역에 대한 투자에 관심이 있지만 투자에 대한 막대한 정부 세금을 줄이기 위해 파트너/에이전트가 필요합니다.

관심이 있으시면 내 이메일(Pingipsolo@gmail.com)로 돌아가서 더 많은 이해를 위해 내 프로젝트에 대한 자세한 내용을 보내고 진행 상황을 확인하십시오.

관련
풍기 파올로
사업 개발 전문가
