### ISSUE TITLE
분류 추가 - 자료구조 2

### ISSUE THREAD

**Issue by VSFe** [tony9402/baekjoon#10]
해시/이진탐색 트리 (Map, Set)/우선순위 큐 내용을 담은 분류 추가를 제안합니다.

트리 자료구조도 필요하긴 하지만, 이건 단독 활용 난이도가 조금 높은 편이라 따로 빼는게 나을 것 같네요...

문제 목록은 여기다 올릴게요

|          순번          |        추천 문제         |        문제 이름         |         난이도          |        풀이 링크         |
| :-----: | :-----: | :-----: | :-----: | :-----: |
| 00 |  :heavy_check_mark:  | <a href="http://boj.kr/1620" target="_blank">나는야 포켓몬 마스터 이다솜</a> | <img height="25px" width="25px=" src="https://static.solved.ac/tier_small/7.svg"/> |                      |
| 01 |  :heavy_check_mark:  | <a href="http://boj.kr/14225" target="_blank">문자열 집합</a> | <img height="25px" width="25px=" src="https://static.solved.ac/tier_small/8.svg"/> |                      |
| 02 |  :heavy_check_mark:  | <a href="http://boj.kr/11279" target="_blank">최대 힙</a> | <img height="25px" width="25px=" src="https://static.solved.ac/tier_small/9.svg"/> |                      |
| 03 |  :heavy_check_mark:  | <a href="http://boj.kr/11286" target="_blank">절댓값 힙</a> | <img height="25px" width="25px=" src="https://static.solved.ac/tier_small/10.svg"/> |                      |
| 04 |  :heavy_check_mark:  | <a href="http://boj.kr/7662" target="_blank">이중 우선순위 큐</a> | <img height="25px" width="25px=" src="https://static.solved.ac/tier_small/11.svg"/> |                      |
| 05 |  :heavy_check_mark:  | <a href="http://boj.kr/2075" target="_blank">N번째 큰 수</a> | <img height="25px" width="25px=" src="https://static.solved.ac/tier_small/12.svg"/> |                      |
| 06 |  :heavy_check_mark:  | <a href="http://boj.kr/4358" target="_blank">생태학</a> | <img height="25px" width="25px=" src="https://static.solved.ac/tier_small/12.svg"/> |                      |
| 07 |  :heavy_check_mark:  | <a href="http://boj.kr/2696" target="_blank">중앙값 구하기</a> | <img height="25px" width="25px=" src="https://static.solved.ac/tier_small/13.svg"/> |                      |
| 08 |                      | <a href="http://boj.kr/9375" target="_blank">패션왕 신해빈</a> | <img height="25px" width="25px=" src="https://static.solved.ac/tier_small/8.svg"/> |                      |
| 09 |                      | <a href="http://boj.kr/1927" target="_blank">최소 힙</a> | <img height="25px" width="25px=" src="https://static.solved.ac/tier_small/10.svg"/> |                      |
| 10 |                      | <a href="http://boj.kr/19583" target="_blank">싸이버개강총회</a> | <img height="25px" width="25px=" src="https://static.solved.ac/tier_small/10.svg"/> |                      |
| 11 |                      | <a href="http://boj.kr/17255" target="_blank">N으로 만들기</a> | <img height="25px" width="25px=" src="https://static.solved.ac/tier_small/11.svg"/> |                      |
| 12 |                      | <a href="http://boj.kr/12764" target="_blank">싸지방에 간 준하</a> | <img height="25px" width="25px=" src="https://static.solved.ac/tier_small/12.svg"/> |                      |
| 13 |                      | <a href="http://boj.kr/1655" target="_blank">가운데를 말해요</a> | <img height="25px" width="25px=" src="https://static.solved.ac/tier_small/14.svg"/> |                      |

**Comment by VSFe** [comment]
아 그리고, 그래프 탐색은 합치는게 좋을 것 같습니다. 각각의 문제에서 어떤 기법을 사용해야 할지 고민해 보는 것도 좋은 공부가 될거라고 생각해요.

**Comment by tony9402** [comment]
문제 뽑을 땐 그래프 탐색으로 하는게 더 좋겠군요.
좋은 제안 감사합니다 :)

**Comment by tony9402** [comment]
1. 제안하신 자료구조 2 추가하였습니다. 
   - 문제 목록 중에 "문자열 집합"이 번호가 달라 수정하였습니다.
   - 생각나는 문제 뽑아서 추가했습니다. 괜찮은 문제는 나중에 천천히 추가해보도록 하죠.
2. BFS, DFS -> 그래프 탐색으로 합쳤습니다.
