### ISSUE TITLE
솔브드 업데이트로 인하여 자동 갱신 기능 중단

### ISSUE THREAD

**Issue by tony9402** [tony9402/baekjoon#137]
어제 솔브드 업데이트로 사용하고 있던 API가 변경되었습니다.
새로운 API를 확인 및 테스트한 후 자동 갱신 기능을 업데이트 하겠습니다.

자동 갱신 기능
   - 백준에 있는 난이도 동기화
   - 알고리즘 분류별로 난이도 순 정렬(추천문제, 기타문제)
       - 추천 문제
           - 기출유형 + 풀어보면 좋은 유형 등, 기출유형
           - 기출유형이 맨 위에 존재
           - 그룹(기출유형, 풀어보면 좋은 유형 등) 별로 난이도 순서(쉬운 순서부터)대로 정렬
       - 기타문제
           - 해당 알고리즘 + 기타(다른 알고리즘)으로 풀 수 있는 문제들
           - 난이도 순서(쉬운 순서부터)대로 정렬

**Comment by tony9402** [comment]
업데이트 완료 했습니다.

**Comment by cieske** [comment]
이번에 솔브닥이 또 업데이트 되어서 그런가... 난이도 표시가 맞지 않는 문제들이 조금 있는 것 같습니다(ex. 문자열 - [부분문자열](https://www.acmicpc.net/problem/16916)) 혹시 업데이트 예정이 있을까요?

**Comment by tony9402** [comment]
해당 깃헙에서 매일 난이도를 갱신하여 자동 Push하는 기능이 있었습니다.
하지만, 현재 Main Branch에 Push하는 권한을 변경하여 자동 갱신되는 부분이 중단됐습니다...

이를 업데이트를 해야하는데 최근에 본 일이 바빠서 계속 미루고 있는 상태입니다 ㅠㅠ
