### ISSUE TITLE
[업데이트 안내] 문제 풀이 컨트리뷰트 가이드라인 업데이트

### ISSUE THREAD

**Issue by tony9402** [tony9402/baekjoon#221]
2021.08.18에 가이드라인 규칙을 수정했습니다. 이 이슈는 약 한달 후에 Closed 될 예정입니다.

업데이트 되기 전  
![image](https://user-images.githubusercontent.com/30228292/129802036-338a5c57-5f4f-46fa-9f91-763ad9a28001.png)

 - C++, Python에만 존재하던 `1 Tab == 4 spaces` 규칙을 모든 언어에 적용했습니다.
 - 새로운 Rule들이 추가되었습니다. 
   - Rule 15 : class보단 struct를 이용해주세요.
   - Rule 23 : 소스코드 일부에 어떤 코드인지 간단한 주석처리를 해주시면 감사하겠습니다. 다른 분들이 보실 때 코드만 볼 경우 이해가 안되는 경우가 있습니다.
   - Rule 24 : 어떤 방식으로 풀었는지 PR을 남기실 때 간단하게 자신의 풀이를 남겨주세요.

**Comment by tallua** [comment]
https://en.cppreference.com/w/cpp/io/basic_ios/tie

cin.tie(false); 가 아니라 cin.tie(nullptr); 가 맞을 것 같습니다.

**Comment by tony9402** [comment]
> https://en.cppreference.com/w/cpp/io/basic_ios/tie
> 
> cin.tie(false); 가 아니라 cin.tie(nullptr); 가 맞을 것 같습니다.

엇 이제 봤네요. 지금보니깐 nullptr가 더 맞는 표현인거 같아서 수정하겠습니다 !

**Comment by tony9402** [comment]
해당 Issue는 한달이 지나 Closed 합니다.
