### ISSUE TITLE
그리디 문제 리스트에 문제가 중복되어 표시됩니다.

### ISSUE THREAD

**Issue by inclue** [tony9402/baekjoon#34]
https://github.com/tony9402/baekjoon/blob/main/greedy/list.md
해당 문서에 행복 유치원이라는 문제가 두번 리스트에 들어가있습니다.

**Comment by tony9402** [comment]
감사합니다. 
중복된 문제 지웠고 나중에 중복 체크하는 것도 만들어놔야겠군요
