### ISSUE TITLE
[해당 레포 업데이트] 개인 일정으로 인해 오랫동안 방치되었던 레포 업데이트 진행합니다.

### ISSUE THREAD

**Issue by tony9402** [tony9402/baekjoon#438]
안녕하세요. tony9402입니다.

현재 대학원 석사과정을 하면서 해당 레포를 자주 관리하기 힘들어졌습니다.
따라서, 올해 4월에 [코드 리뷰어](https://github.com/tony9402/baekjoon/issues/405#issue-1199764988)를 뽑았습니다.
혹시 모를 PR 악용을 막고자 main branch에 "Branch protection rule"을 설정해놓았습니다. 이로 인해, 문제 난이도 자동 업데이트와 데일리 문제 추천 시스템이 정지하게 되었습니다.

이를 다시 작동시키기 위해서 레포를 아래와 같이 분리하려고 합니다.
 - 문제집 및 데일리 문제 추천 : 현재 레포지토리에서 솔루션 파트를 제외한 나머지를 유지 및 리뷰어(Collaborator) 제외
 - 문제 추천 솔루션 : 현재 레포지토리에서 솔루션 파트만 새로운 레포지토리로 생성 및 현재 레포지토리에 등록된 리뷰어(Collaborator) 추가

최대한 빠른 시일 내에 다시 정상작동할 수 있게 업데이트 해보겠습니다.

좋은 아이디어가 있으시면 언제든 알려주시면 환영입니다. 😄 

감사합니다.

+ 2022.10.02 : [솔루션 레포 공개](https://github.com/tony9402/solutions_for_baekjoon_problems)

**Comment by juheon-jeong** [comment]
문제 추천 솔루션 부분에서 새로운 레포지토리로 생성하신다고 하셨는데, 혹시 생성한 레포지토리 주소도 올려주실 수 있나요? 그리고 문제 추천 솔루션에서 솔루션이 올라오지 않은 문제에 대해서 PR을 올려도 되나요??

**Comment by tony9402** [comment]
@juheon-jeong 
Q. 문제 추천 솔루션 부분에서 새로운 레포지토리로 생성하신다고 하셨는데, 혹시 생성한 레포지토리 주소도 올려주실 수 있나요?
A. 현재 정리중에 있으며 완료될 시 공개할 예정입니다.

Q. 그리고 문제 추천 솔루션에서 솔루션이 올라오지 않은 문제에 대해서 PR을 올려도 되나요??
A.  네 새로운 레포에서 없는 솔루션인 경우 PR 올리셔도 됩니다.
