### ISSUE TITLE
알고리즘 문제 - 백준 강의실 배정

### ISSUE THREAD

**Issue by nnnlog** [tony9402/baekjoon#5]
1. 문제 이름 : 강의실 배정
2. 온라인 저지 사이트 이름 : 백준
3. 문제 링크 : https://www.acmicpc.net/problem/11000
4. 알고리즘 유형 : 그리디, 정렬
5. 난이도 (솔브드 기준으로 변환) : 골드 5

**Comment by tony9402** [comment]
https://github.com/tony9402/baekjoon/tree/main/greedy 업로드 완료
